# Code generated by go.einride.tech/sage. DO NOT EDIT.
# To learn more, see .sage/main.go and https://github.com/einride/sage.

.DEFAULT_GOAL := all

cwd := $(dir $(realpath $(firstword $(MAKEFILE_LIST))))
sagefile := $(abspath $(cwd)/.sage/bin/sagefile)

# Setup Go.
go := $(shell command -v go 2>/dev/null)
export GOWORK ?= off
ifndef go
SAGE_GO_VERSION ?= 1.25.5
export GOROOT := $(abspath $(cwd)/.sage/tools/go/$(SAGE_GO_VERSION)/go)
export PATH := $(PATH):$(GOROOT)/bin
go := $(GOROOT)/bin/go
os := $(shell uname | tr '[:upper:]' '[:lower:]')
arch := $(shell uname -m)
ifeq ($(arch),x86_64)
arch := amd64
endif
$(go):
	$(info installing Go $(SAGE_GO_VERSION)...)
	@mkdir -p $(dir $(GOROOT))
	@curl -sSL https://go.dev/dl/go$(SAGE_GO_VERSION).$(os)-$(arch).tar.gz | tar xz -C $(dir $(GOROOT))
	@touch $(GOROOT)/go.mod
	@chmod +x $(go)
endif

.PHONY: $(sagefile)
$(sagefile): $(go)
	@cd .sage && $(go) mod tidy && $(go) run .

.PHONY: sage
sage:
	@$(MAKE) $(sagefile)

.PHONY: update-sage
update-sage: $(go)
	@cd .sage && $(go) get go.einride.tech/sage@latest && $(go) mod tidy && $(go) run .

.PHONY: clean-sage
clean-sage:
	@git clean -fdx .sage/tools .sage/bin .sage/build

.PHONY: all
all: $(sagefile)
	@$(sagefile) All

.PHONY: generate-workflows
generate-workflows: $(sagefile)
	@$(sagefile) GenerateWorkflows

.PHONY: go-format
go-format: $(sagefile)
	@$(sagefile) GoFormat

.PHONY: go-lint
go-lint: $(sagefile)
	@$(sagefile) GoLint

.PHONY: go-mod-tidy
go-mod-tidy: $(sagefile)
	@$(sagefile) GoModTidy

.PHONY: go-test
go-test: $(sagefile)
	@$(sagefile) GoTest

.PHONY: go-vulncheck
go-vulncheck: $(sagefile)
	@$(sagefile) GoVulncheck

.PHONY: plenary-test
plenary-test: $(sagefile)
	@$(sagefile) PlenaryTest

.PHONY: plenary-test-file
plenary-test-file: $(sagefile)
ifndef test_path
	 $(error missing argument test_path="...")
endif
	@$(sagefile) PlenaryTestFile "$(test_path)"

.PHONY: query-format
query-format: $(sagefile)
	@$(sagefile) QueryFormat

.PHONY: query-lint
query-lint: $(sagefile)
	@$(sagefile) QueryLint

.PHONY: query-lint-fix
query-lint-fix: $(sagefile)
	@$(sagefile) QueryLintFix

.PHONY: update-sage-ci
update-sage-ci: $(sagefile)
	@$(sagefile) UpdateSageCi

.PHONY: zensical-build
zensical-build: $(sagefile)
	@$(sagefile) ZensicalBuild

.PHONY: zensical-serve
zensical-serve: $(sagefile)
	@$(sagefile) ZensicalServe

.PHONY: zensical-sync
zensical-sync: $(sagefile)
	@$(sagefile) ZensicalSync
