# SAFE TO CUSTOMIZE - This file is copied once and not overwritten during sync
# Source: https://github.com/fredrikaverpil/github

version: '3'

vars:
  TASKFILES:
    sh: find . -type f -name "Taskfile.*.yml" -not -path "*/node_modules/*" -not -path "*/.git/*" | sort

tasks:
  default:
    desc: List all available tasks
    silent: true
    cmds:
      - task --list

  all:
    desc: Run all static checking and tests
    cmds:
      - task: format
      - task: lint
      - task: test

  format:
    desc: Run format task from all taskfiles
    cmds:
      - cmd: task -t {{.TASKFILE}} format
        for:
          var: TASKFILES
          split: "\n"
          as: TASKFILE

  lint:
    desc: Run lint task from all taskfiles
    cmds:
      - cmd: task -t {{.TASKFILE}} lint
        for:
          var: TASKFILES
          split: "\n"
          as: TASKFILE

  test:
    desc: Run test task from all taskfiles
    cmds:
      # - cmd: task -t {{.TASKFILE}} test
      #   for:
      #     var: TASKFILES
      #     split: "\n"
      #     as: TASKFILE
      - task: test-busted

  test-busted:
    desc: Run tests with busted via lazy.nvim minit
    cmds:
      - cmd: nvim -l ./spec/busted.lua spec

  test-clean:
    desc: Run tests with busted via lazy.nvim minit
    cmds:
      - cmd: rm -rf .tests

  install:
    desc: Run install task from all taskfiles
    cmds:
      - cmd: task -t {{.TASKFILE}} install
        for:
          var: TASKFILES
          split: "\n"
          as: TASKFILE

  clean:
    desc: Clean .tests directory
    cmds:
      - rm -rf .tests
