name: Bug Report
description: File a bug/issue.
title: "bug: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report and help improve neotest-golang! :heart:
        Please note: usage questions such as "How do I...?" belong in [discussions](https://github.com/fredrikaverpil/neotest-golang/discussions) and will be moved there (or closed).
  - type: checkboxes
    attributes:
      label: Did you check docs and existing issues?
      description: Make sure you checked all of the below before submitting an issue.
      options:
        - label: I have read the [documentation](https://github.com/fredrikaverpil/neotest-golang/blob/main/README.md).
          required: true
        - label: I have searched the existing [issues](https://github.com/fredrikaverpil/neotest-golang/issues).
          required: true
  - type: input
    attributes:
      label: "Neovim version (nvim -v)"
      placeholder: "0.10.0 commit db1b0ee3b30f"
    validations:
      required: true
  - type: input
    attributes:
      label: "Operating system/version"
      placeholder: "MacOS 14.5"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Please include any related errors you see in Neovim.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Do this
        2. Do that
        3. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
