// Code generated by sage-ci. DO NOT EDIT.

package main

import (
	"context"

	"github.com/fredrikaverpil/sage-ci/targets"
)

// GoModTidy runs the goModTidy target for configured Go modules.
func GoModTidy(ctx context.Context) error {
	return targets.GoModTidy(ctx, cfg)
}

// GoFormat runs the goFormat target for configured Go modules.
func GoFormat(ctx context.Context) error {
	return targets.GoFormat(ctx, cfg)
}

// GoLint runs the goLint target for configured Go modules.
func GoLint(ctx context.Context) error {
	return targets.GoLint(ctx, cfg)
}

// GoTest runs the goTest target for configured Go modules.
func GoTest(ctx context.Context) error {
	return targets.GoTest(ctx, cfg)
}

// GoVulncheck runs the goVulncheck target for configured Go modules.
func GoVulncheck(ctx context.Context) error {
	return targets.GoVulncheck(ctx, cfg)
}

// GenerateWorkflows regenerates CI workflows for the configured platform.
func GenerateWorkflows(ctx context.Context) error {
	return targets.GenerateWorkflows(cfg)
}
