// Code generated by bld. DO NOT EDIT.
// To add custom tasks, create additional .go files in this directory.

package main

import (
	"github.com/fredrikaverpil/bld/tasks"
	"github.com/goyek/goyek/v3"
	"github.com/goyek/x/boot"
)

// All tasks are automatically created based on Config.
var t = tasks.New(Config)

func main() {
	goyek.SetDefault(t.All)
	boot.Main()
}
