name: stale
# https://github.com/actions/stale

on:
  schedule:
    - cron: "0 7 * * 1-5"
  workflow_dispatch:
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This issue has been open for **20 days** with no activity. Remove the stale label or add a comment or it will be closed in **10 days**."
          stale-pr-message: "This PR has been open for **20 days** with no activity. Remove the stale label or add a comment or it will be closed in **10 days**."
          close-issue-message: "This issue was closed because it has been stalled for 30 days with no activity."
          close-pr-message: "This PR was closed because it has been stalled for 30 days with no activity."
          days-before-stale: 20
          days-before-close: 10
          exempt-pr-labels: dependencies,bug
          exempt-issue-labels: dependencies
