name: python

# NOTE: disabled for this project.
on: {}

# on:
#   workflow_dispatch:
#   pull_request:
#   push:
#     branches:
#       - main

# NOTE: This file will not be re-synced automatically. Add project-specifics here.

jobs:
  ci:
    uses: fredrikaverpil/github/.github/workflows/python.yml@main
    with:
      python-versions: '["3.13"]'
      os-versions: '["ubuntu-latest"]'
