name: dependabot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1" # Monday at 8am

jobs:
  title:
    uses: fredrikaverpil/github/.github/workflows/gen-dependabot.yml@main
    # with:
    #   file_patterns: "go.mod,uv.lock"
    #   exclude_patterns: "**/tests/**,path/to/specific/directory/**"
    secrets: inherit
