name: vuln
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * 1"
jobs:
  go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.23, 1.24.0-rc.3]
    env:
      GOTOOLCHAIN: local
      GOTOOLCHAIN_RESOLVE_PRIVATE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install tools
        run: make install-vuln-go
      - name: Run vulnerability check
        run: make vuln-go
